name: Build and Deploy to GKE

on:
    push:
        branches:
            - main

env:
    PROJECT_ID: cloud-build-demo-363112
    IMAGE: pytest
    DOCKER_REPO_URL: https://us-central1-docker.pkg.dev/cloud-build-demo-363112/gha

jobs:
    setup-build-publish-deploy:
        name: Setup, Build, Publish
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - id: "auth"
              uses: "google-github-actions/auth@v2"
              with:
                  credentials_json: "${{ secrets.SA_KEY }}"

            - name: "Set up Cloud SDK"
              uses: "google-github-actions/setup-gcloud@v2"

            - name: "Use gcloud CLI"
              run: "gcloud info"

            # Configure Docker to use the gcloud command-line tool as a credential
            # helper for authentication
            - run: |-
                  gcloud --quiet auth configure-docker us-central1-docker.pkg.dev

            # Build the Docker image
            - name: Build
              run: |-
                  docker build \
                    --tag "$DOCKER_REPO_URL/$IMAGE:${GITHUB_SHA::7}" \
                    .

            # Push the Docker image to Google Container Registry
            - name: Publish
              run: |-
                  docker push "$DOCKER_REPO_URL/$IMAGE:${GITHUB_SHA::7}"
