name: Build and Deploy to GKE

on:
    push:
        branches:
            - main

env:
    PROJECT_ID: cloud-build-demo-363112
    IMAGE: demo-nodejs-dev
    DOCKER_REPO_URL: us-central1-docker.pkg.dev/cloud-build-demo-363112/gha

jobs:
    setup-build-publish-deploy:
        name: Setup, Build, Publish
        runs-on: arc-runner-set-dev-fixed1

        # Add "id-token" with the intended permissions.
        permissions:
            contents: "read"
            id-token: "write"

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            ## SA from metadata on k8s using workload identity
            # - id: "auth"
            #   uses: "google-github-actions/auth@v2"
            #   with:
            #       project_id: "1049042308740"
            #       service_account: "gh-actions-dev@cloud-build-demo-363112.iam.gserviceaccount.com"
            #       workload_identity_provider: "projects/1049042308740/locations/global/workloadIdentityPools/github-actions-dev/providers/github"

            - name: "Set up Cloud SDK"
              uses: "google-github-actions/setup-gcloud@v2"

            - name: "Use gcloud CLI"
              run: "gcloud info"

            # Configure Docker to use the gcloud command-line tool as a credential
            # helper for authentication
            - run: |-
                  gcloud --quiet auth configure-docker us-central1-docker.pkg.dev

            # Build the Docker image
            - name: Build
              run: |-
                  docker build \
                    --tag "$DOCKER_REPO_URL/$IMAGE:${GITHUB_SHA::7}" \
                    .

            # Push the Docker image to Google Container Registry
            - name: Publish
              run: |-
                  docker push "$DOCKER_REPO_URL/$IMAGE:${GITHUB_SHA::7}"
